#!/bin/bash

_check_conf_files="${_cur_repo}-${_arch}-cfg.conf ${_cur_repo}-${_arch}-makepkg.conf user.conf"
_load_conf_files="${_cur_repo}-${_arch}-cfg.conf ${_cur_repo}-${_arch}-makepkg.conf user.conf"

check_configs() {
            title2 "Checking configs"

            for conffile in ${_check_conf_files}
            do
                status_start "${conffile}"

                if [ -e "_buildscripts/${conffile}" ] ; then
                    status_ok 
                else
                    status_fail
                    error "${conffile} not available. Exiting..."
                    newline
                    exit 1
                fi
            done
}

load_configs() {
            title2 "Loading configs"

            local ret=0

            for conffile in ${_load_conf_files}
            do
                source _buildscripts/${conffile} 2>&1 || ret=$?

                if [ ${ret} -gt 0 ]; then
                    status_fail
                    error "Sourcing ${conffile} failed. Exiting..."
                    newline
                    exit 1
                fi
            done

                if [ "$_cur_repo" = "core" ] ; then
                        . "_buildscripts/core-${_arch}-pkgs.conf"
                        
                elif [ "$_cur_repo" = "core-testing" ] ; then
                        . "_buildscripts/core-testing-${_arch}-pkgs.conf"

                elif [ "$_cur_repo" = "platform" ] ; then
                        . "_buildscripts/platform-${_arch}-pkgs.conf"
                
                elif [ "$_cur_repo" = "platform-testing" ] ; then
                        . "_buildscripts/platform-testing-${_arch}-pkgs.conf"

                elif [ "$_cur_repo" = "desktop" ] ; then
                        . "_buildscripts/desktop-${_arch}-pkgs.conf"
                        
                elif [ "$_cur_repo" = "desktop-testing" ] ; then
                        . "_buildscripts/desktop-testing-${_arch}-pkgs.conf"

                elif [ "$_cur_repo" = "apps" ] ; then
                        . "_buildscripts/apps-${_arch}-pkgs.conf"

                elif [ "$_cur_repo" = "apps-testing" ] ; then
                        . "_buildscripts/apps-testing-${_arch}-pkgs.conf"

		elif [ "$_cur_repo" = "apps-unstable" ] ; then
                        . "_buildscripts/apps-unstable-${_arch}-pkgs.conf"

                elif [ "$_cur_repo" = "bundles" ] ; then
                        . "_buildscripts/bundles-${_arch}-pkgs.conf"

		elif [ "$_cur_repo" = "bundles-testing" ] ; then
                        . "_buildscripts/bundles-testing-${_arch}-pkgs.conf"

		elif [ "$_cur_repo" = "xorg18" ] ; then
                        . "_buildscripts/xorg18-${_arch}-pkgs.conf"

                else
                        echo "ERROR: no repo specified!!!"
                        exit 1
                fi
}
